declare module 'mkdirp'
declare module 'koa-conditional-get'
declare module 'koa2-cors'
declare module 'koa-etag'
declare module 'koa-rewrite'
declare module 'bcryptjs'
declare module 'koa-helmet'
declare module 'koa-ratelimit'